language: bash

notifications:
  email: false

env:
  global:
    - INSTALL_TARGET=./target

    - BINTRAY_USERNAME=pypt

    # BINTRAY_API_KEY:
    - secure: "QIB7dKW9jeJVGtj5HX/PihRI9eymQ+Fj8mA/9gIfIcxGI34TdE7biLL23aTWjKObo9nJ1mV/aHiMFVI3/GVRwQetz//5qdV2YI4jKUkWitTrl3k4PcrwdrSu2AbR2xe/p0fQt4Vd0HD9O7A+FVczTdtyY8i1tYFzZjckEhZru+LoL9NMCpEJmwBed71x6Bcz76PV/aW3jw/tzCnds575JTxOnqMs62+uHWsLHzhWQZ+vgsebQ7HZH2mDRz7l3ti+4N3ww1BIKrm0THS7s91UdP7xx5Y/d4602LSzi4uH5gjbF3ASyTHEaaDUvE8G4uWICBcDcbJPOHbRclV4euDJDug1hq7d45HlVovgahsje0Dlm5zAe5Met5VZe6m8xWClRQ+XFLCxvpZn91/chztYyvxKbL/sLeR+wuUqOjdFVhkcrdkX4OJWa3AF2WlqpulkDUpbc2rK3jnC679lqVZG1xtrtUSd43+f30uXMUovvaIre6AXB83eHPsc9hOoOk8Gk2hGIt7x/GlkuAKm9ZeJAskUcSWjWN6eIBDPPaDkYp2O2x75Z5F6OkCOqbUV57nuIyuWLsMuVAtt6WnAqoMthbuC8b3xsBCOYogQ3RQhzBx8utLVI2QLd4IWKJf7hbiVQWIcANJWgVZovfDP5n+sR4K1QBTAB3sWBjdun2PjkOE="

    - BINTRAY_REPOSITORY_TGZ=mecab-ipadic-neologd-tgz
    - BINTRAY_REPOSITORY_DEB=mecab-ipadic-neologd-deb
    - BINTRAY_REPOSITORY_RPM=mecab-ipadic-neologd-rpm

    - BINTRAY_DESCRIPTOR_TGZ=$HOME/bintray-tgz.json
    - BINTRAY_DESCRIPTOR_DEB=$HOME/bintray-deb.json
    - BINTRAY_DESCRIPTOR_RPM=$HOME/bintray-rpm.json

install:
  - gem install --no-ri --no-rdoc fpm

cache: apt

addons:
  apt:
    packages:
      - build-essential
      - curl
      - file
      - git
      - libmecab-dev
      - make
      - mecab
      - mecab-ipadic-utf8
      - rpm
      - ruby
      - ruby-dev
      - xz-utils

before_script:
  - mkdir $INSTALL_TARGET

script:
  - bash ./bin/install-mecab-ipadic-neologd --prefix `readlink -m $INSTALL_TARGET`

  # Create .tgz
  - >
      if [[ "$TRAVIS_TAG" != "" ]]; then python2.7 ./libexec/create_package.py
      --type tgz
      --input_dir $INSTALL_TARGET
      --version_tag $TRAVIS_TAG
      --bintray_descriptor_file $BINTRAY_DESCRIPTOR_TGZ
      --bintray_repository_name $BINTRAY_REPOSITORY_TGZ
      --bintray_username $BINTRAY_USERNAME; fi

  # Create .deb
  - >
      if [[ "$TRAVIS_TAG" != "" ]]; then python2.7 ./libexec/create_package.py
      --type deb
      --input_dir $INSTALL_TARGET
      --version_tag $TRAVIS_TAG
      --bintray_descriptor_file $BINTRAY_DESCRIPTOR_DEB
      --bintray_repository_name $BINTRAY_REPOSITORY_DEB
      --bintray_username $BINTRAY_USERNAME; fi

  # Create .rpm
  - >
      if [[ "$TRAVIS_TAG" != "" ]]; then python2.7 ./libexec/create_package.py
      --type rpm
      --input_dir $INSTALL_TARGET
      --version_tag $TRAVIS_TAG
      --bintray_descriptor_file $BINTRAY_DESCRIPTOR_RPM
      --bintray_repository_name $BINTRAY_REPOSITORY_RPM
      --bintray_username $BINTRAY_USERNAME; fi

deploy:

  # Deploy .tgz
  - provider: bintray
    file: "$BINTRAY_DESCRIPTOR_TGZ"
    user: "$BINTRAY_USERNAME"
    key: "$BINTRAY_API_KEY"
    skip_cleanup: true
    on:
      tags: true

  # Deploy .deb
  - provider: bintray
    file: "$BINTRAY_DESCRIPTOR_DEB"
    user: "$BINTRAY_USERNAME"
    key: "$BINTRAY_API_KEY"
    skip_cleanup: true
    on:
      tags: true

  # Deploy .rpm
  - provider: bintray
    file: "$BINTRAY_DESCRIPTOR_RPM"
    user: "$BINTRAY_USERNAME"
    key: "$BINTRAY_API_KEY"
    skip_cleanup: true
    on:
      tags: true
